version: '3'

services:
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        restart: always
        volumes:
            - frontend_node_modules:/app/node_modules
        depends_on: 
            - backend

    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            - backend_node_modules:/app/node_modules
        restart: always
    
    webserver:
        build:
            dockerfile: Dockerfile
            context: ./webserver
        ports:
            - 8080:80
        depends_on:
            - backend
            - frontend

volumes:
    backend_node_modules:
    frontend_node_modules: